### ISSUE TITLE
Support sox for macOS

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/voice-recorder#1]
The program doesn't work on macOS because it doesn't have `arecord`. Sox should do the trick too, probably called as `rec`. According to the man page, the `-r` and `-c` options you currently use for `arecord` should work the same with `sox`. The `-f S16_LE` option should be different: I believe this becomes `-e signed-integer -b 16 -L`. And the device can be specified as `-t coreaudio DEVICENAME`.

I haven't tested this yet, but this should work.

**Comment by koenvervloesem** [comment]
@synesthesiam can you take a look at this? The same commands should run on Linux too (maybe add a flag to voice-recorder to use arecord/aplay versus sox rec/play). I can't get this to record anything on macOS, and I'm not sure if it's the fault of my external microphone or sox. Maybe it's just that sox outputs something else than arecord.

**Comment by synesthesiam** [comment]
OK, I've added a `--record-command` and a `--play-command` option. You can use short names like this:

```sh
$ python3 record.py --record-command sox --play-command sox ...
```

This should use the default audio device on both Mac and Linux. Let me know!

**Comment by koenvervloesem** [comment]
Thanks, recording and playing works on macOS with this record and play command set to `sox`, at least with the changes in https://github.com/synesthesiam/voice-recorder/pull/2.
